version: '3.4'

services:
  desafio_backend_stefanini.api:
    image: ${DOCKER_REGISTRY-}desafio_backend_stefanini_api
    depends_on:
    - sqldata
    build:
      context: .
      dockerfile: desafio_backend_stefanini/desafio_backend_stefanini.API/Dockerfile
    environment:
      DBConnection: "Data Source=sqldata,1433;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=Stefanini@123"

  desafio_backend_stefanini.front:
    image: ${DOCKER_REGISTRY-}desafio_backend_stefanini_front
    build:
      context: .
      dockerfile: desafio_backend_stefanini/desafio_backend_stefanini/Dockerfile
      args:
        - skip_client_build=true
    ports:
      - "7243:7243"
      - "44491:44491"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Stefanini@123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"